locass_orga_salle_new:
    path:     /new
    defaults: { _controller: "LocassOrgaBundle:Default:newsalle" }
    methods:  [GET, POST]
locass_orga_salle_index:
    path:     /
    defaults: { _controller: "LocassOrgaBundle:Default:indexsalle" }
    methods:  [GET, POST]

