essai_index:
    path:     /
    defaults: { _controller: "TestmongoStoreBundle:Essai:index" }
    methods:  GET

essai_show:
    path:     /{id}/show
    defaults: { _controller: "TestmongoStoreBundle:Essai:show" }
    methods:  GET

essai_new:
    path:     /new
    defaults: { _controller: "TestmongoStoreBundle:Essai:new" }
    methods:  [GET, POST]

essai_edit:
    path:     /{id}/edit
    defaults: { _controller: "TestmongoStoreBundle:Essai:edit" }
    methods:  [GET, POST]

essai_delete:
    path:     /{id}/delete
    defaults: { _controller: "TestmongoStoreBundle:Essai:delete" }
    methods:  DELETE
