test_index:
    path:     /
    defaults: { _controller: "TestmongoStoreBundle:Test:index" }
    methods:  GET

test_show:
    path:     /{id}/show
    defaults: { _controller: "TestmongoStoreBundle:Test:show" }
    methods:  GET

test_new:
    path:     /new
    defaults: { _controller: "TestmongoStoreBundle:Test:new" }
    methods:  [GET, POST]

test_edit:
    path:     /{id}/edit
    defaults: { _controller: "TestmongoStoreBundle:Test:edit" }
    methods:  [GET, POST]

test_delete:
    path:     /{id}/delete
    defaults: { _controller: "TestmongoStoreBundle:Test:delete" }
    methods:  DELETE
