<?php

namespace Locass\SallesBundle\Repository;

/**
 * SallesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SallesRepository extends \Doctrine\ORM\EntityRepository
{
}
