locass_orga_homepage:
    path:     /
    defaults: { _controller: LocassOrgaBundle:Default:index }

locass_orga_group:
    resource: "@LocassOrgaBundle/Resources/config/routing/group.yml"
    prefix:   /group

locass_orga_salle:
    resource: "@LocassOrgaBundle/Resources/config/routing/salle.yml"
    prefix:   /salle
