locass_bands:
    resource: "@LocassBandsBundle/Resources/config/routing.yml"
    prefix:   /bands

locass_bands_register:
    path:     /register/band/{token}
    defaults: { _controller: LocassUserBundle:Default:registerband }
    methods:  GET

locass_salles_register:
    path:     /register/salle/{token}
    defaults: { _controller: LocassUserBundle:Default:registersalle }
    methods:  GET

locass_orgas_register:
    path:     /register/orga/{token}
    defaults: { _controller: LocassUserBundle:Default:registerorga }
    methods:  GET

locass_orga:
    resource: "@LocassOrgaBundle/Resources/config/routing.yml"
    prefix:   /orga

locass_salles:
    resource: "@LocassSallesBundle/Resources/config/routing.yml"
    prefix:   /salles

locass_admin:
    resource: "@LocassAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

locass_user:
    resource: "@LocassUserBundle/Resources/config/routing.yml"
    prefix:   /

testmongo_store:
    resource: "@TestmongoStoreBundle/Resources/config/routing.yml"
    prefix:   /mongotest

app:
    resource: "@AppBundle/Controller/"
    prefix: /appb
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
