locass_user:
    resource: "@LocassUserBundle/Resources/config/routing.yml"
    prefix:   /

testmongo_store:
    resource: "@TestmongoStoreBundle/Resources/config/routing.yml"
    prefix:   /mongotest

app:
    resource: "@AppBundle/Controller/"
    prefix: /app
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
