# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    locass_user.registration_listener:
        class: Locass\UserBundle\EventListener\RegistrationListener
        arguments: []
        tags:
          - { name: kernel.event_subscriber }
    locass_user.check_email_society:
        class: Locass\UserBundle\Service\checkEmailSociety
        arguments:
          - "@doctrine.odm.mongodb.document_manager"