Locass\BandsBundle\Entity\Bands:
    type: entity
    table: null
    repositoryClass: Locass\BandsBundle\Repository\BandsRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idfosuser:
            type: integer
            unique: false
        nom:
            type: string
            length: 255
        prenom:
            type: string
            length: 255
        adresse:
            type: string
            length: 255
        email:
            type: string
            length: 255
        band:
            type: string
            length: 255
            column: Band
        origine:
            type: boolean
            column: Origine
        dateinscr:
            type: datetimetz
            column: Dateinscr
    lifecycleCallbacks: {  }
