<?php

namespace Locass\UserBundle\Repository;

/**
 * CountrycodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountrycodeRepository extends \Doctrine\ORM\EntityRepository
{
}
