<?php

namespace Testmongo\StoreBundle\Repository;

/**
 * EssaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EssaiRepository extends \Doctrine\ORM\EntityRepository
{
}
